// https: //d2lang.com/tour/shapes/

layout: elk
direction: right

classes: {
  site_box: {style: {stroke-dash: 0; fill: transparent; stroke: "lightblue"; font-color: "white"; border-radius: 12; stroke-width: 6}; grid-columns: 3}

  dc_node: {shape: cylinder; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  srv_node: {shape: package; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  server_node: {shape: package; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  net_node: {shape: diamond; style: {fill: "orange"; stroke: "white"; stroke-width: 2; font-color: "white"}}

  // User Elements
  user_node: {shape: person; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  voip_node: {shape: callout; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}

  // Hardware
  hardware_node: {shape: page; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  edge_node: {shape: cloud; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  peripheral_node: {shape: circle; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  iot_node: {shape: oval; style: {fill: "blue"; stroke: "white"; stroke-width: 2; font-color: "white"}}
  lcd_node: {shape: document; style: {fill: "orange"; stroke: "white"; stroke-width: 2; font-color: "blue"}}
}

BRK: {
  // Brockville, Ontario
  class: site_box
  label: "BRK - Brockville (CA)\n192.168.136.0/24"
  EXADONBRK001: {class: iot_node; label: "EXADONBRK001\nVxWorks\nDonut Mach\n.101"}
  EXALAPBRK001: {class: user_node; label: "EXALAPBRK001\nWin 11\nTour Laptop\n.50"}
  EXAMBPBRK001: {class: user_node; label: "EXAMBPBRK001\nmacOS\nStaff MBP\n.51"}
  EXAPHNBRK001: {class: user_node; label: "EXAPHNBRK001\niOS 17\niPhone\n.61"}
  EXAPBXBRK001: {class: voip_node; label: "EXAPBXBRK001\n3CX PBX\nVOIP Server\n.200"}
}

MIA: {
  // Vice City, Florida
  class: site_box
  label: "MIA - Miami (US)\n192.168.135.0/24"
  EXACOFMIA001: {class: iot_node; label: "EXACOFMIA001\nVxWorks\nCoffee Mach\n.102"}
  EXAPHNMIA001: {class: user_node; label: "EXAPHNMIA001\niOS 17\niPhone\n.61"}
  EXALAPMIA001: {class: user_node; label: "EXALAPMIA001\nmacOS\nTour MBP\n.51"}
}

ABD: {
  // Aberdeen
  class: site_box
  label: "ABD - Aberdeen, UK\n192.168.224.0/24\n"
  EXAPHNABD001: {class: user_node; label: "EXAPHNABD001\nDHCP\niOS 17.x\nStaff Phone"}
  EXAPHNABD002: {class: user_node; label: "EXAPHNABD002\nDHCP\niOS 17.x\nStaff Phone"}
  EXAMBPABD001: {class: user_node; label: "EXAMBPABD001\nDHCP\nmacOS Sonoma 14.2.1\nStaff MacBook"}
  EXAMBPABD002: {class: user_node; label: "EXAMBPABD002\nDHCP\nmacOS Sonoma 14.2.1\nStaff MacBook"}
}

DUN: {
  // Dundee
  class: site_box
  label: "DUN - Dundee\n192.168.25.0/24"
  EXADUNDC01: {class: dc_node; label: "EXADUNDC01\n192.168.25.10\nWin Srv\nDC 01"}
  EXAFWLDUN001: {class: net_node; label: "EXAFWLDUN001\n192.168.25.1\nFortiOS\nFW"}
  EXASWIDUN001: {class: net_node; label: "EXASWIDUN001\n192.168.25.2\nCisco\nSwitch"}
  EXASBCDUN001: {class: net_node; label: "EXASBCDUN001\n192.168.25.15\n3CX\nSBC"}
  EXAWKSDUN001: {class: user_node; label: "EXAWKSDUN001\n192.168.25.30\nWin 10\nWKS"}
  EXALAPDUN001: {class: user_node; label: "EXALAPDUN001\n192.168.25.50\nmacOS\nMBP"}
  EXAPRNDUN001: {class: iot_node; label: "EXAPRNDUN001\n192.168.25.200\nKyocera\nMFP"}
}

PER: {
  // Perth
  class: site_box
  label: "DUN - Dundee\n192.168.173.0/24"
  EXADUNDC01-: {class: dc_node; label: "EXAPERDC01\n192.168.173.10\nWin Srv\nDC 01"}
  EXAFWLPER001: {class: net_node; label: "EXAFWLDUN001\n192.168.173.1\nFortiOS\nFW"}
  EXASWIPER001: {class: net_node; label: "EXASWIDUN001\n192.168.173.2\nCisco\nSwitch"}
  EXAPRNPER001: {class: iot_node; label: "EXAPRNPER001\n192.168.173.20\nHP MFP LaserJet\nMulti-function printer / scanner"}
  EXASBCPER001: {class: net_node; label: "EXASBCPER001\n192.168.173.30\n3CX SBC Debian\n3CX SBC – VOIP gateway for Perth"}
  EXANIXPER001: {class: srv_node; label: "EXANIXPER001\n192.168.173.40\nSolaris 11.5\nMIDI/Music archive server for Fiction Factory"}
  EXANASPER001: {class: peripheral_node; label: "EXANASPER001\n192.168.173.50\nSynology DSM 7.1\nFile storage for user profiles & music archive"}
  EXACVMPER001: {class: iot_node; label: "EXACVMPER001\n192.168.173.60\nSmart Bakery Vending Machine SP100\nScone Palace vending machine"}
  EXAMBPPER001: {class: user_node; label: "EXAMBPPER001\n192.168.173.70\nmacOS Ventura 13.5\nMacBook Pro assigned to staff"}
  EXASURPER001: {class: user_node; label: "EXASURPER001\n192.168.173.71\nWindows 11 Pro\nSurface Laptop assigned to staff"}
  EXAPHNPER001: {class: user_node; label: "EXAPHNPER001\n192.168.173.82\nYealink T46G\nDesk VOIP phone"}
  EXAPHNPER002: {class: user_node; label: "EXAPHNPER002\n192.168.173.83\nYealink T46G\nDesk VOIP phone"}
  EXAPHNPER003: {class: user_node; label: "EXAPHNPER003\n192.168.173.83\nYealink T46G\nDesk VOIP phone"}
  EXAPHNPER004: {class: user_node; label: "EXAPHNPER004\n192.168.173.84\nYealink T46G\nDesk VOIP phone"}
}

GLA: {
  // G Postcode
  class: site_box
  label: "GLA - Glasgow\n192.168.21.0/24"
  EXAGLADC001: {class: dc_node; label: "EXAGLADC001\n192.168.21.10\nWin Srv\nDC 01"}
  EXAFWLGLA001: {class: net_node; label: "EXAFWLGLA001\n192.168.21.1\nFortiOS\nFW"}
  EXASWIGLA001: {class: net_node; label: "EXASWIGLA001\n192.168.21.2\nCisco\nSwitch"}
  EXASBCGLA001: {class: net_node; label: "EXASBCGLA001\n192.168.21.15\n3CX\nSBC"}
  EXAWKSGLA001: {class: user_node; label: "EXAWKSGLA001\n192.168.21.30\nWin 10\nWKS"}
  EXALAPGLA001: {class: user_node; label: "EXALAPGLA001\n192.168.21.50\nmacOS\nMBP"}
  EXAPRGLA001: {class: iot_node; label: "EXAPRGLA001\n192.168.21.200\nRicoh\nMFP"}
  EXARACGLA001: {class: net_node; label: "EXARACGLA001\n192.168.21.250\niDRAC\nRemote"}
}

CLY: {
  // Cyldebank
  class: site_box
  label: "CLY - Clydebank, UK\n192.168.141.0/24\n"
  EXADCCLY01: {class: server_node; label: "EXADCCLY01\n192.168.141.9\nWindows Server 2022\nDomain Controller"}
  EXADCCLY02: {class: server_node; label: "EXADCCLY02\n192.168.141.11\nWindows Server 2022\nDomain Controller"}
  EXASRVCLY001: {class: server_node; label: "EXASRVCLY001\n192.168.141.20\nRocky Linux\nOracle DB Server"}
  EXAFWLCLY001: {class: edge_node; label: "EXAFWLCLY001\n192.168.141.1\nFortiOS 7.6.5\nFirewall"}
  EXASWICLY001: {class: net_node; label: "EXASWICLY001\n192.168.141.2\nCisco Catalyst 9300\nCore Switch"}
  EXAILOCLY001: {class: hardware_node; label: "EXAILOCLY001\n192.168.141.30\nHPE iLO5\niLO Management"}
  EXARACCLY001: {class: hardware_node; label: "EXARACCLY001\n192.168.141.30\nHP iLO5\nDRAC Management"}
  EXASBCCLY001: {class: voip_node; label: "EXASBCCLY001\n192.168.141.49\n3CX SBC\nVOIP Gateway"}
  EXASURCLY001: {class: user_node; label: "EXASURCLY001\n192.168.141.51\nWindows 11 Pro\nTouring Surface"}
  EXAPHNGLA001: {class: user_node; label: "EXAPHNGLA001\nDHCP\niOS 26.1\nTouring Phone"}
  EXATABGLA001: {class: user_node; label: "EXATABGLA001\n192.168.141.62\niOS 26.2\nSetlist Tablet"}
}

EDI: {
  // Edinburgh
  class: site_box
  label: "EDI - Edinburgh, UK\n192.168.131.0/24\n"
  EXAEDIDC01: {class: server_node; label: "EXAEDIDC01\n192.168.3.20\nWindows Server 2019\nDomain Controller"}
  EXADCEDI03: {class: server_node; label: "EXADCEDI03\n192.168.131.10\nWindows Server 2022\nDomain Controller"}
  EXAWKSEDI001: {class: user_node; label: "EXAWKSEDI001\n192.168.131.150\nWindows 10 Pro\nShared Workstation"}
  EXALAPEDI098: {class: user_node; label: "EXALAPEDI098\n192.168.131.108\nWindows 11 Pro\nPool Laptop"}
  EXARACEDI001: {class: hardware_node; label: "EXARACEDI001\n192.168.131.2\nDell iDRAC9\nManagement"}
  EXASWIEDI001: {class: net_node; label: "EXASWIEDI001\n192.168.131.5\nCisco 2960X\nFloor Switch"}
  EXASWIEDI002: {class: net_node; label: "EXASWIEDI002\n192.168.131.6\nCisco 2960X\n48-port Switch"}
  EXASBCEDI001: {class: voip_node; label: "EXASBCEDI001\n192.168.131.49\n3CX SBC\nSession Border Controller"}
  EXATEAEDI001: {class: iot_node; label: "EXATEAEDI001\n192.168.131.16\nSiemens EQ700\nCoffee Machine"}
}

// South of Hadrian's Wall

NEW: {
  // Newcastle
  class: site_box
  label: "NEW - Newcastle\n192.168.191.0/24"
  EXASBCNEW001: {class: net_node; label: "SBC\n.15"}
  EXASRVNEW001: {class: srv_node; label: "Ubuntu Srv\n.20"}
  EXARACNEW001: {class: net_node; label: "iDRAC\n.250"}
  EXASWINEW001: {class: net_node; label: "Switch\n.2"}
  EXAWKSNEW099: {class: user_node; label: "Win 11\n.30"}
}

MCR: {
  // Manchester
  class: site_box
  label: "MCR - Manchester, UK\n192.168.161.0/24\n"
  EXAMCRDC01: {class: server_node; label: "EXAMCRDC01\n192.168.61.10\nWindows Server 2022\nDomain Controller"}
  EXAMCRDC02: {class: server_node; label: "EXAMCRDC02\n192.168.61.11\nWindows Server 2022\nDomain Controller"}
  EXALAPMCR001: {class: user_node; label: "EXALAPMCR001\n192.168.228.19\nWindows 11 Ent\nMgmt Laptop"}
  EXALAPMCR002: {class: user_node; label: "EXALAPMCR002\n192.168.161.150\nWindows 11 Ent\nStaff Laptop"}
  EXAWKSMCR001: {class: user_node; label: "EXAWKSMCR001\n192.168.161.152\nWindows 10 Ent\nFront Desk PC"}
  EXAWKSMCR002: {class: user_node; label: "EXAWKSMCR002\n192.168.161.153\nWindows 10 Ent\nFinance PC"}
  EXAPRNMCR001: {class: peripheral_node; label: "EXAPRNMCR001\n192.168.161.16\nPrinter\nNetwork Printer"}
  EXARACMCR001: {class: hardware_node; label: "EXARACMCR001\n192.168.161.2\nHPE iLO5\nManagement"}
  EXASWIMCR001: {class: net_node; label: "EXASWIMCR001\n192.168.161.5\nCisco Catalyst 9300\nDist Switch"}
  EXASBCMCR001: {class: voip_node; label: "EXASBCMCR001\n192.168.161.49\n3CX SBC\nVOIP Gateway"}
}

LIV: {
  // Liverpool
  class: site_box
  label: "LIV - Liverpool, UK\n192.168.151.0/24\n"
  EXALIVDC01: {class: server_node; label: "EXALIVDC01\n192.168.51.11\nWindows Server 2025\nDomain Controller"}
  EXASVRLIV001: {class: server_node; label: "EXASVRLIV001\n192.168.151.10\nWindows Server 2022\nFile Server"}
  EXAMBPLIV001: {class: user_node; label: "EXAMBPLIV001\n192.168.151.150\nmacOS Tahoe 26.0.1\nPool MacBook"}
  EXAMACLIV001: {class: user_node; label: "EXAMACLIV001\n192.168.151.152\nmacOS Tahoe 26.0.1\nPool iMac"}
  EXARDRLIV002: {class: security_node; label: "EXARDRLIV002\n192.168.31.16\nHID Signo\nBadge Reader"}
  EXABPSLIV001: {class: security_node; label: "EXABPSLIV001\n192.168.151.17\nHID Omnikey\nBadge Station"}
  EXARACLIV001: {class: hardware_node; label: "EXARACLIV001\n192.168.151.2\nHPE iLO5\nManagement"}
  EXASWILIV001: {class: net_node; label: "EXASWILIV001\n192.168.151.5\nCisco Catalyst 9200\nCore Switch"}
  EXASBCLIV001: {class: voip_node; label: "EXASBCLIV001\n192.168.151.49\n3CX SBC\nVOIP Gateway"}
}

BIR: {
  // Birmingham
  class: site_box
  label: "BIR - Birmingham, UK\n192.168.121.0/24\n"
  EXADCBIR02: {class: server_node; label: "EXADCBIR02\n192.168.121.11\nWindows Server 2022\nDomain Controller"}
  EXASRVBIR001: {class: server_node; label: "EXASRVBIR001\n192.168.121.20\nRocky Linux\nOracle DB Node"}
  EXAFWLBIR001: {class: edge_node; label: "EXAFWLBIR001\n192.168.121.1\nPalo Alto PanOS\nFirewall"}
  EXASWIBIR001: {class: net_node; label: "EXASWIBIR001\n192.168.121.2\nCisco Catalyst 9300\nCore Switch"}
  EXASWIBIR002: {class: net_node; label: "EXASWIBIR002\n192.168.121.20\nCisco Catalyst\n48-port Switch"}
  EXAILOBIR001: {class: hardware_node; label: "EXAILOBIR001\n192.168.121.30\nHPE iLO5\nILO Management"}
  EXARACBIR001: {class: hardware_node; label: "EXARACBIR001\n192.168.121.6\nDell DRAC\nDRAC Management"}
  EXASBCBIR001: {class: voip_node; label: "EXASBCBIR001\n192.168.121.49\n3CX SBC\nVOIP Gateway"}
  EXAMBPBIR001: {class: user_node; label: "EXAMBPBIR001\n192.168.121.41\nmacOS Sonoma\nTouring MacBook"}
  EXATABBIR001: {class: user_node; label: "EXATABBIR001\n192.168.121.61\nLineage OS\nSetlist Tablet"}
  EXAPHNBIR001: {class: user_node; label: "EXAPHNBIR001\nDHCP\nLineage OS\nTouring Phone"}
  EXALCDBIR001: {class: lcd_node; label: "EXALCDBIR001\n192.168.121.30\nNEC PlasmaSync\nNOC Display"}
}

LND: {
  // Avocado Central
  class: site_box
  label: "LND - London, UK\n192.168.20.0/24\n"
  EXALNDDC01: {class: server_node; label: "EXALNDDC01\n192.168.2.20\nWindows Server 2022\nDomain Controller"}
  EXAWKSLND001: {class: user_node; label: "EXAWKSLND001\n192.168.20.150\nWindows 11 Pro\nHot Desk PC"}
  EXAPRNLND001: {class: peripheral_node; label: "EXAPRNLND001\n192.168.20.16\nPrinter\nXerox WorkCentre"}
  EXARTRLND001: {class: net_node; label: "EXARTRLND001\n192.168.20.254\nCisco ISR 4331\nWAN Router"}
  EXAFWLLND001: {class: edge_node; label: "EXAFWLLND001\n192.168.20.1\nCisco ASA 5516-X\nFirewall"}
  EXARACLND001: {class: hardware_node; label: "EXARACLND001\n192.168.20.2\nDell iDRAC9\nManagement"}
  EXASWILND001: {class: net_node; label: "EXASWILND001\n192.168.20.5\nCisco Catalyst 9300\nCore Switch"}
  EXASBCLND001: {class: voip_node; label: "EXASBCLND001\n192.168.20.49\n3CX SBC\nVOIP Gateway"}
  EXAPRNLND002: {class: iot_node; label: "EXAPRNLND002\nDHCP\nProCAT Stylus`nSteno Writer – Court Device"}
}

ODE: {
  // Odense, Fyn
  class: site_box
  label: "ODE - Odense, Danmark (Primay Europe Site)\n192.168.66.0/24\n\n"
  EXAODEDC01: {class: server_node; label: "EXAODEDC01\n192.168.7.20\nWindows Server 2022\nDomain Controller"}
  EXAMACODE001: {class: user_node; label: "EXAMACODE001\n192.168.66.150\nmacOS Tahoe 26.0.1\nDesign iMac"}
  EXAMBPODE002: {class: user_node; label: "EXAMBPODE002\n192.168.66.151\nmacOS Tahoe 26.0.1\nExec MacBook"}
  EXAMUSODE001: {class: iot_node; label: "EXAMUSODE001\n192.168.66.18\nPureline 128V\nRetro Jukebox"}
  // Geographic Landmark Glyph
  EXADSBODE001: {shape: hexagon; style: {fill: "#ff0000"; stroke: "#000000"}; label: "LANDMARK\nStorebæltsbroen\n(Great Belt Bridge)"}
}

CPH: {
  // København, Lorry
  class: site_box
  label: "CPH - Christianshavn, København\n192.168.31.0/24\n"
  EXACLKCPH001: {class: iot_node; label: "EXACLKCPH001\n192.168.228.18\nMeinberg M300\nNTP Clock"}
  EXARACCPH001: {class: hardware_node; label: "EXARACCPH001\n192.168.31.2\nDell iDRAC9\nManagement"}
  EXASWICPH001: {class: net_node; label: "EXASWICPH001\n192.168.31.5\nTP-Link\nSwitch"}
  EXASBCCPH001: {class: voip_node; label: "EXASBCCPH001\n192.168.31.49\n3CX SBC\nGateway"}
  EXATVSCPH001: {class: iot_node; label: "EXATVSCPH001\n192.168.31.17\nBella Krøniklen\nTV"}
  EXAFWLCPH001: {class: edge_node; label: "EXAFWLCPH001\n192.168.31.1\nFortiOS\nFirewall"}
  EXAWKSCPH001: {class: user_node; label: "EXAWKSCPH001\n192.168.31.30\nWin 10\nWorkstation"}
  EXAOELCPH001: {class: iot_node; label: "EXABERCPH001\n192.168.31.105\nVxWorks\nAlbani Vending Machine\nModel: Rottehullet"}
}

KGE: {
  // Køge, Syd Jyland
  class: site_box
  label: "KGE - Køge, Danmark\n192.168.56.0/24\n"
  EXAKBRDC01: {class: server_node; label: "EXAKBRDC01\n192.168.5.20\nWindows Server 2016\nDomain Controller"}
  EXAWAPKGE001: {class: net_node; label: "EXAWAPKGE001\n192.168.56.5\nUniFi U6-Pro\nAccess Point"}
  EXAPRNKGE001: {class: peripheral_node; label: "EXAPRNKGE001\n192.168.56.16\nHP LaserJet\nMFP Printer"}
}

BRA: {
  // Bramming, Syd Jyland
  class: site_box
  label: "BRA - Bramming, Danmark\n192.168.110.0/24\n"
  EXABRADC01: {class: server_node; label: "EXABMGDC01\n192.168.10.20\nWindows Server 2019\nDomain Controller"}
  EXAWKSBRA001: {class: user_node; label: "EXAWKSBMG001\n192.168.110.150\nWindows 10 Pro\nLogistics PC"}
  EXASWIBRA001: {class: net_node; label: "EXASWIBMG001\n192.168.110.5\nCisco 2960L\nSite Switch"}
}

EBJ: {
  // Esjberg, Syd Jyland
  class: site_box
  label: "ESB - Esbjerg, Danmark\n192.168.111.0/24\n"
  EXAESBDC01: {class: server_node; label: "EXAEBJDC01\n192.168.11.20\nWindows Server 2022\nDomain Controller"}
  EXAPRNESB001: {class: peripheral_node; label: "EXAPRNEBJ001\n192.168.111.16\nBrother MFC\nOffice Printer"}
  EXAFWLESB001: {class: edge_node; label: "EXAFWLEBJ001\n192.168.111.1\nUDM Pro\nSite Gateway"}
  EXASWIESB001: {class: net_node; label: "EXASWIEBJ001\n192.168.111.5\nUniFi Switch\nCore Switch"}
  EXAWKSESB001: {class: user_node; label: "EXAWKSEBJ001\n192.168.111.150\nWindows 11 Pro\nPort Ops PC"}
}

AAR: {
  // Aarhus, Nord Jyland
  class: site_box
  label: "AAR - Aarhus, Danmark\n192.168.99.0/24\n"
  EXAAARDC01: {class: server_node; label: "EXAAARDC01\n192.168.9.20\nWindows Server 2022\nDomain Controller"}
  EXAMBPAAR001: {class: user_node; label: "EXAMBPAAR001\n192.168.99.150\nmacOS Sonoma\nMarketing Mac"}
  EXAWKSAAR001: {class: user_node; label: "EXAWKSAAR001\n192.168.99.151\nWindows 11 Pro\nSales PC"}
  EXASWIAAR001: {class: net_node; label: "EXASWIAAR001\n192.168.99.5\nCisco 2960X\nOffice Switch"}
  EXASBCAAR001: {class: voip_node; label: "EXASBCAAR001\n192.168.99.49\n3CX SBC\nVOIP Gateway"}
  EXAWAPAAR001: {class: net_node; label: "EXAWAPAAR001\n192.168.99.10\nUniFi U6-LR\nAccess Point"}
}

MUC: {
  // Munich, Barvaria
  class: site_box
  label: "MUC - Munich, Germany\n192.168.88.0/24\n"
  EXAMUCDC01: {class: server_node; label: "EXAMUCDC01\n192.168.8.20\nWindows Server 2022\nDomain Controller"}
  EXAWKSMUC001: {class: user_node; label: "EXAWKSMUC001\n192.168.88.150\nWindows 11 Pro\nEng Workstation"}
  EXAWKSMUC002: {class: user_node; label: "EXAWKSMUC002\n192.168.88.151\nWindows 11 Pro\nEng Workstation"}
  EXASWIMUC001: {class: net_node; label: "EXASWIMUC001\n192.168.88.5\nCisco 9200L\nSite Switch"}
  EXAFWLMUC001: {class: edge_node; label: "EXAFWLMUC001\n192.168.88.1\nFortiGate 60F\nFirewall"}
  EXASBCMUC001: {class: voip_node; label: "EXASBCMUC001\n192.168.88.49\n3CX SBC\nVOIP Gateway"}
}

BON: {
  // Bonn, North Rhine-Westphalia
  class: site_box
  label: "BON - Bonn\n192.168.228.0/24"
  EXAVCUBON001: {class: iot_node; label: "EXAVCUBON001\n192.168.228.115\nPoly OS\nVCU"}
  EXACAMBON001: {class: iot_node; label: "EXACAMBON001\n192.168.228.130\nLinux\nCam 01"}
  EXAWKSBON001: {class: user_node; label: "EXAWKSBON001\n192.168.228.30\nWindows 10\nWKS 01"}
  EXAWKSBON002: {class: user_node; label: "EXAWKSBON002\n192.168.228.31\nWindows 10\nWKS 02"}
  EXALAPBON001: {class: user_node; label: "EXALAPBON001\n192.168.228.50\nmacOS\nMacbook Pro"}
  EXALAPBON002: {class: user_node; label: "EXALAPBON002\n192.168.228.51\nWindows 11\nLaptop"}
  EXACAMBON003: {class: iot_node; label: "EXACAMBON003\n192.168.228.131\nLinux\nCam 02"}
  EXATVSBON001: {class: iot_node; label: "EXATVSBON001\n192.168.228.170\nTizen\nTV"}
  EXARACBON001: {class: net_node; label: "EXARACBON001\n192.168.228.250\niDRAC\nRemote"}
  EXASWIBON001: {class: net_node; label: "EXASWIBON001\n192.168.228.2\nSwitchOS\nSwitch"}
  EXASBCBON001: {class: net_node; label: "EXASBCBON001\n192.168.228.15\n3CX SBC\nVOIP Gateway"}
}

HAM: {
  // Hamburg, Hamburg
  class: site_box
  label: "HAM - Hamburg, Germany\n192.168.112.0/24\n"
  EXAHAMDC01: {class: server_node; label: "EXAHAMDC01\n192.168.12.20\nWindows Server 2022\nDomain Controller"}
  EXAFWLHAM001: {class: edge_node; label: "EXAFWLHAM001\n192.168.112.1\nFortiGate 80F\nFirewall"}
  EXASWIHAM001: {class: net_node; label: "EXASWIHAM001\n192.168.112.5\nCisco 9300\nCore Switch"}
  EXAWKSHAM001: {class: user_node; label: "EXAWKSHAM001\n192.168.112.150\nWindows 11 Pro\nLogistics PC"}
  EXASBCHAM001: {class: voip_node; label: "EXASBCHAM001\n192.168.112.49\n3CX SBC\nVOIP Gateway"}
}

BER: {
  // West Berlin
  class: site_box
  label: "BER - Berlin, Germany\n192.168.113.0/24\n"
  EXABERDC01: {class: server_node; label: "EXABERDC01\n192.168.13.20\nWindows Server 2022\nDomain Controller"}
  EXAFWLBER001: {class: edge_node; label: "EXAFWLBER001\n192.168.113.1\nFortiGate 100F\nFirewall"}
  EXASWIBER001: {class: net_node; label: "EXASWIBER001\n192.168.113.5\nCisco 9500\nCore Switch"}
  EXASBCBER001: {class: voip_node; label: "EXASBCBER001\n192.168.113.49\n3CX SBC\nVOIP Gateway"}
  EXAWKSBER001: {class: user_node; label: "EXAWKSBER001\n192.168.113.150\nWindows 11 Pro\nAdmin PC"}
  EXAPRNBER001: {class: peripheral_node; label: "EXAPRNBER001\n192.168.113.16\nRicoh IMC\nNetwork Printer"}
}

VIE: {
  // Vienna, Austria
  class: site_box
  label: "VIE - Vienna, Austria\n192.168.116.0/24\n"
  EXASRVVIE001: {class: server_node; label: "EXASRVVIE001\nLinux Srv\n.20"}
  EXASBCVIE001: {class: voip_node; label: "EXASBCVIE001\n3CX SBC\n.49"}
}

// VPN Links

// North America
BRK <-> MIA: vDSL {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
MIA <-> DUN: Satellite Uplink {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}

// Scotland
GLA <-> EDI: Fiber {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
DUN <-> GLA: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
DUN <-> EDI: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
ABD <-> DUN: Leased Line {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
PER <-> DUN: Leased Line {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
PER <-> EDI: Leased Line {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
ABD <-> EDI: Leased Line {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
GLA <-> CLY: PPTP {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}

// England
EDI -> MCR: PPTP (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
EDI <-> NEW: PPTP (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
GLA <-> MCR: PPTP (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
MCR <-> LIV: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
// TODO: force directions so it matches geography
BIR <-> LND: "ISDN (Bonded)" {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
NEW <-> AAR: ISDN (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}

// Danmark
BRA -> ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
ESB -> ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
AAR -> ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
KGE -> ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
ODE -> CPH: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
ESB <- ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
BRA <- ESB: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
BRA <-> ODE: Fiber (Bonded) {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}

// Deutschland
BON <-> BER: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
HAM <-> BER: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
BON <-> HAM: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}
BON <-> MUC: ISDN {style: {stroke: "lightblue"; stroke-width: 4; stroke-dash: 5}}

LEGEND: {
  // LEGEND
  style: {stroke: "#333333"; fill: "#f8f9fa"; font-color: "#000000"}
  label: |md
    ```text

    LEGEND & MASTER CONVENTIONS
    ═══════════════════════════
    BLUE Cylinder:  Domain Controllers / Servers
    GREEN Box:      User Devices (Laptops, Phones)
    ORANGE Hex:     Networking (Switches, SBCs, FW)
    PURPLE Box:     IoT / Specialized Hardware

    DEVICE NAMING & DEMO DATA CONVENTIONS
    ═════════════════════════════════════

    Company Suffixes:
    Name                             Region             Legal Form      Notes
    ──────────────────────────────── ────────────────── ──────────────  ────────────────────────────────────────
    Example Music (England) Ltd      United Kingdom     Ltd             England & Wales Jurisdiction
    Example Music (Scotland) Ltd     United Kingdom     Ltd (SCxxxxxx)  Scottish company numbers start with "SC"
    Example Music (Danmark) ApS      Denmark            ApS             Danmark Aktieselskab
    Example Music (Deutschland) GmbH Deutschland        GmbH            German Registered (Limited Liability)
    Example Music (Österreich) GmbH  Österreich         GmbH            Austrian Registered (Limited Liability)
    Example Music (CA) Inc.          North America      Inc.            Canadian Federal Corporation
    Example Music (US) LLC.          North America      LLC.            United States Limited Liability Company

    Site  Location                   Region             Subnet               Landline Range
    ────  ─────────────────────────  ─────────────────  ──────────────────   ─────────────────────────────────
    AAR   Aarhus, Danmark            Denmark            192.168.xxx.x        +45  00  000  xxx
    ABR   Aberdeen, Scotland         United Kingdom     192.168.224.0/24     +44 1224 496 0xxx
    BIR   Birmingham, England        United Kingdom     192.168.121.0/24     +44 121  496 0xxx
    BON   Bonn, Deutschland          Deutschland        192.168.228.0/24     +49 228  555  xxx
    BRA   Bramming, Danmark          Denmark            192.168.xxx.x        +45  00  000  xxx
    BRD   Berlin, Deutschland        Deutschland        192.168.113.0/24     +49 311  555  xxx
    BRK   Brockville, Canada         North America      192.168.136.0/24     +1  613  555 6xxx
    CLY   Clydebank, Scotland        United Kingdom     192.168.141.0/24     +44 141  496 00xx
    CPH   Copenhagen, Denmark        Denmark            192.168.231.0/24     +45  00  000  xxx
    DUN   Dundee, Scotland           United Kingdom     192.168.138.0/24     +44 163  249 60xx
    EDI   Edinburgh, Scotland        United Kingdom     192.168.131.0/24     +44 131  496 0xxx
    ESJ   Esbjerg, Danmark           Denmark            192.168.xxx.x        +45  00  000  xxx
    FAX   Faxe, Danmark              Denmark            192.168.246.0/24     +45  00  000  xxx
    GLA   Glasgow, Scotland          United Kingdom     192.168.141.0/24     +44 141  496 01xx
    KGE   Køge, Danmark              Denmark            192.168.265.0/24     +45  00  000  xxx
    KOR   Korsør, Danmark            Denmark            192.168.238.0/24     +45  00  000  xxx
    LIV   Liverpool, England         United Kingdom     192.168.151.0/24     +44 151  496 0xxx
    LND   London, England            United Kingdom     192.168.20.0/24      +44 207  496 0xxx
    MCR   Manchester, England        United Kingdom     192.168.161.0/24     +44 161  715 xxxx
    MIA   Miami, United States       North America      192.168.135.0/24     +1  305  555 xxxx
    MUN   Munich, Deutschland        Deutschland        192.168.189.0/24     +49 893  555 33xx
    NEW   Newcastle, England         United Kingdom     192.168.191.0/24     +44 191  496 0xxx
    ODE   Odense, Danmark            Denmark            192.168.126.0/24     +45  00  000  xxx
    VIE   Vienna, Österreich         Österreich         192.168.xxx.0/24     +43 800  078  0xx
  |
}
